export default [
  ["CE", "func"],
  ["C", "func"],
  ["<=", "func"],
  ["/", "op"],
  [7, "num"],
  [8, "num"],
  [9, "num"],
  ["x", "op"],
  [4, "num"],
  [5, "num"],
  [6, "num"],
  ["-", "op"],
  [1, "num"],
  [2, "num"],
  [3, "num"],
  ["+", "op"],
  ["+-", "mod"],
  [0, "num"],
  [".", "num"],
  ["=", "func"]
];
